<?php

namespace Devblock\CourseGrabBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotifyUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotifyUserRepository extends EntityRepository
{
}
