<?php

namespace Devblock\CourseGrabBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * notifyUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class notifyUserRepository extends EntityRepository
{
}
