devblock_course_grab_homepage:
    path:     /
    defaults: { _controller: DevblockCourseGrabBundle:Default:index }
    
devblock_course_grab_test:
    path:     /test
    defaults: { _controller: DevblockCourseGrabBundle:Test:index }
    
devblock_course_grab_test_email:
    path:     /test/email
    defaults: { _controller: DevblockCourseGrabBundle:NotifyApi:postNotify }

devblock_course_grab_api_post_course:
    path: /api/post/courses
    defaults: { _controller: DevblockCourseGrabBundle:CourseApi:postCourses }
    #methods: POST
    requirements:
        _format: json
         
devblock_course_grab_api_post_filters:
    path: /api/post/filters
    defaults: { _controller: DevblockCourseGrabBundle:CourseApi:postFilters }
    methods: POST
    requirements:
        _format: json

devblock_course_grab_api_post_count_pages:
    path: /api/post/count/pages
    defaults: { _controller: DevblockCourseGrabBundle:CourseApi:postCountPages }
    methods: POST
    requirements:
        _format: json

devblock_course_grab_api_post_notify:
    path: /api/post/notify
    defaults: { _controller: DevblockCourseGrabBundle:NotifyApi:postNotify }
    methods: POST
    requirements:
        _format: json
