devblock_course_grab_homepage:
    path:     /
    defaults: { _controller: DevblockCourseGrabBundle:Default:index }
    
devblock_course_grab_test:
    path:     /test
    defaults: { _controller: DevblockCourseGrabBundle:Test:index }

devblock_course_grab_api_post_course:
    path: /api/post/courses
    defaults: { _controller: DevblockCourseGrabBundle:Api:postCourses }
    requirements:
        _format: json
        methods:  POST
